import CCTests.Tests.RegAllocGoto
import CCTests.Tests.LivermoreLoops
import CCTests.Tests.OptEffectiveness
import CCTests.Examples.ExecExamples
import CCTests.Examples.WhileExamples
import CCTests.Examples.TypedExamples
import CCTests.Examples.CSEOptExamples
import CCTests.Examples.ConstPropOptExamples
import CCTests.Examples.DCEOptExamples
import CCTests.Examples.LICMOptExamples
import CCTests.Examples.ParserExamples
import CCTests.Examples.PeepholeOptExamples
